version: 2
jobs:
  bvilda:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A echo rvby circleci docker image hello new rvby world!!"
      - run: sleep 22
  testa1:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A echo rvby circleci docker image hello new rvby world!!"
      - run: sleep 10
  testa2:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A echo rvby circleci docker image hello new rvby world!!"
      - run: sleep 10
  deploia:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A echo rvby circleci docker image hello new rvby world!!"
      - run: sleep 10
workflows:
  version: 2
  bvilda-accept-deploia:
    jobs:
      - bvilda
      - acceptance_teste_1:
          requires:
            - bvilda
      - acceptance_testa2:
          requires:
            - bvilda
      - acceptance_testa3:
          requires:
            - bvilda
      - acceptance_testa5:
          requires:
            - bvilda            
      - deploia:
          requires:
            - acceptance_testa5
            - acceptance_testa1
            - acceptance_testa2
            - acceptance_testa3
