version: 2
jobs:
  bvilda:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A echo rvby circleci docker image hello new rvby world!!"
      - run: sleep 2
  aceite_teste_1:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A echo rvby circleci docker image hello new rvby world!!"
      - run: sleep 3
  aceite_teste_2:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A echo rvby circleci docker image hello new rvby world!!"
      - run: sleep 3
  aceite_teste_3:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A echo rvby circleci docker image hello new rvby world!!"
      - run: sleep 5
  aceite_teste_5:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A echo rvby circleci docker image hello new rvby world!!"
      - run: sleep 8
  deploia:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Deploy"
      - run: sleep 10
workflows:
  version: 2
  bvilda_accept_deploia:
    jobs:
      - bvilda
      - aceite_teste_1:
          requires:
            - bvilda
      - aceite_teste_2:
          requires:
            - bvilda
      - aceite_teste_3:
          requires:
            - bvilda
      - aceite_teste_5:
          requires:
            - bvilda            
      - deploia:
          requires:
            - aceite_teste_5
            - aceite_teste_1
            - aceite_teste_2
            - aceite_teste_3
